[package]
name = "nexus-executor"
version.workspace = true
edition.workspace = true

[dependencies]
anyhow.workspace = true
async-trait = "0.1"
tokio.workspace = true
nexus-api = { path = "../nexus-api" }
nexus-sandbox = { path = "../nexus-sandbox" }
tracing.workspace = true
