[package]
name = "nexus-term"
version.workspace = true
edition.workspace = true

[dependencies]
alacritty_terminal = { workspace = true }
thiserror = { workspace = true }
tracing = { workspace = true }
